name: "sleep-apnea-dataset-generation"
version: "1.0.0"
steps:
  - "download"
  - "extract"
  - "process"

data:
  ids:
#    - "00000995"
#    - "00000999"
#    - "00001000"
#    - "00001008"
#    - "00001245"
    - "00001367"
  targets:
    - "Hypopnea"
    - "ObstructiveApnea"
    - "normal"  # 新增：补充实际存在的正常类别

download:
  mode: "local" #local or gcs
  bucket_name: null
  edf_urls:
    - "https://download.scidb.cn/download?fileId=61a0ca3f89f14b48842cf1ce&path=/V3/APNEA_EDF/00001014-100507/00001014-100507[001].edf&fileName=00001014-100507%5B001%5D.edf"
    - "https://download.scidb.cn/download?fileId=61a0ca3f89f14b48842cf1cd&path=/V3/APNEA_EDF/00001014-100507/00001014-100507[002].edf&fileName=00001014-100507%5B002%5D.edf"
    - "https://download.scidb.cn/download?fileId=61a0ca3f89f14b48842cf1cc&path=/V3/APNEA_EDF/00001014-100507/00001014-100507[003].edf&fileName=00001014-100507%5B003%5D.edf"
    - "https://download.scidb.cn/download?fileId=61a0ca3f89f14b48842cf1cb&path=/V3/APNEA_EDF/00001014-100507/00001014-100507[004].edf&fileName=00001014-100507%5B004%5D.edf"


  rml_urls:
    - "https://download.scidb.cn/download?fileId=61a0ca3f89f14b48842ceec4&path=/V3/APNEA_RML/00001014-100507.rml&fileName=00001014-100507.rml"
  catalog_file: "file_catalog.txt"  # 保持不变

audio:
  data_channels: "Mic"
  edf_step_size: 10000000
  sample_rate: 48000
  clip_length: 30
  clip_overlap: 15
  n_mels: 128
  ids_to_process:
#    - "00000995"
#    - "00000999"
#    - "00001000"
#    - "00001008"
#    - "00001245"
    - "00001367"
  image_size: 224

training:
  batch_size: 32
  num_epochs: 20
  learning_rate: 0.001
  dropout: 0.3
  num_classes: 3  # 与 data.targets 数量一致（Hypopnea + ObstructiveApnea）
  val_split: 0.2
  test_split: 0.1

paths:
  root: "data"
  dataset_file_name: "data"
  # 新增：音频处理结果保存路径（解决 AttributeError）
  audio_save_path: "data/processed/audio"  # 相对于 root 的路径
  # 补充：信号处理结果路径（与训练代码对应）
  signals_path: "data/processed/signals"  # 生成的 pickle 文件保存路径
  augmented_save_path: "data/processed/augmented_signals"  # 增强数据保存路径
  wgan_generator_path: "models/end2end/wgan_generator.pth"  # WGAN预训练模型路径



data_augmentation:
  enable: True  # 是否启用针对性增强
  target_classes: [1, 2]  # 目标增强类别（1=Hypopnea，2=ObstructiveApnea，对应标签映射）
  balance_baseline: 0  # 平衡基准类别（0=normal，以该类样本数为目标）
  augment_method: "wgan"  # 增强方法（wgan/traditional）
  wgan_batch_size: 32  # WGAN生成批次大小
#
## 标签映射（统一管理类别与索引对应关系）
#label_mapping:
#  normal: 0
#  Hypopnea: 1
#  ObstructiveApnea: 2